# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CineRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineRoom
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
	pod 'Alamofire', '~> 5.4'
	pod 'youtube-ios-player-helper'
	pod 'lottie-ios'

end
